branch-defaults:
  master:
    environment: timeinc-docker-dev
global:
  application_name: sloos
  default_ec2_keyname: ti-use1-bdprod-docker
  default_platform: 64bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.2 (Puma)
  default_region: sa-east-1
  profile: eb-cli
  sc: git